### ISSUE TITLE
TypeError: UniDepthV2.__init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by smart4654154** [cvlab-kaist/PF3plat#2]
Error executing job with overrides: ['+experiment=re10k', 'data_loader.train.batch_size=3']
Traceback (most recent call last):
  File "/home/zzl/Download/PF3plat-main/src/main.py", line 119, in train
    encoder, encoder_visualizer = get_encoder(cfg.model.encoder)
  File "/home/zzl/Download/PF3plat-main/src/model/encoder/__init__.py", line 17, in get_encoder
    encoder = encoder(cfg)
  File "/home/zzl/Download/PF3plat-main/src/model/encoder/encoder_costvolume.py", line 81, in __init__
    self.uni_depth = UniDepthV2.from_pretrained("lpiccinelli/unidepth-v2-vitl14")
  File "/home/zzl/anaconda3/envs/zzl_pf3plat/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/zzl/anaconda3/envs/zzl_pf3plat/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 571, in from_pretrained
    instance = cls._from_pretrained(
  File "/home/zzl/anaconda3/envs/zzl_pf3plat/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 791, in _from_pretrained
    model = cls(**model_kwargs)
TypeError: UniDepthV2.__init__() missing 1 required positional argument: 'config'‘

could you help me?thank you

**Comment by SunghwanHong** [comment]
Hi, 
https://github.com/lpiccinelli-eth/UniDepth/issues/35
